[project]
name = "mas-ai-interview"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "langchain-gigachat>=0.3.12",
    "langchain-openai>=0.3.35",
    "langgraph>=1.0.1",
    "python-dotenv>=1.2.1",
]
